version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: WEB2_BookStore
        MYSQL_ROOT_PASSWORD:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
      volumes:
        - db_data:/var/lib/mysql
        - ./database:/docker-entrypoint-initdb.d

volumes:
  db_data:
